---
- hosts: all
  become: true
  vars:
    users:
    - mundo
    - admin
  tasks:
    - name: Make sure we can connect
      ping:
    - name: Create admin group
      group:
        name:  admin
        state: present
    - name: "Create user accounts and add users to groups"
      user:
        name: "{{ item }}"
        groups: "admin"
      with_items: "{{ users }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"
